In [1]:
import tensorflow as tf # importar libreria TensoFlow como tf

In [4]:
constante = tf.constant([2.0,3,4],dtype=tf.float32, name='constante1') #definimos nuestra constante float32, grafica computacional osea aun los valores no estan definidos

In [3]:
print(constante) #aun no imprime los valores que tiene constante

Tensor("constante1:0", shape=(3,), dtype=float32)


In [5]:
apartado = tf.placeholder(tf.float32, name='apartado1') # se define placeholder= variable vacia en un principio pero que se va llenando

In [11]:
print(apartado) #igualque con la constante no deja imprimir pq no se ha asignado un valor

Tensor("apartado1:0", dtype=float32)


In [12]:
variable = tf.Variable(3,dtype=tf.float32,name='variable1') #tipo de dato variable, si puede cambiar durante la ejecucion

In [13]:
print (variable) #tampoco deja imprimir, pq no se ha corrido la grafica computacional

<tf.Variable 'variable1_1:0' shape=() dtype=float32_ref>


In [18]:
matriz = tf.zeros([3, 4], tf.int32, name='matriz') # se define una matriz de ceros, para despues alterarla

In [19]:
print (matriz)

Tensor("matriz_2:0", shape=(3, 4), dtype=int32)


In [20]:
inicializar = tf.global_variables_initializer() # corremos la sesion, primero se inicializan las variables

In [21]:
sess = tf.Session() # esta variable es la encargada de correr la grafica computacional

In [23]:
sess.run(inicializar) # ahora ya corio la grafica computacional

In [24]:
print (sess.run(constante)) # ahora si imprime los valores con la funcion sess.run

[2. 3. 4.]


In [25]:
print (sess.run(matriz)) #muestra los datos de la matriz

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [26]:
print (sess.run(variable)) #muestra los datos de la matriz

3.0


In [29]:
constante

<tf.Tensor 'constante1:0' shape=(3,) dtype=float32>

In [30]:
print (sess.run(matriz)) 

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [31]:
sess.run(matriz)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [41]:
multiplicacion = apartado*constante #funcion multiplicacion

In [45]:
print (sess.run(multiplicacion,feed_dict={apartado:[[15,10,5]]})) # a la hora de correr la multiplicacion le asigna valores a apartado

[[30. 30. 20.]]


In [52]:
# multiplicacion de matices necesita llevar la forma (mxn) x (nxm) =(m,m)
a = tf.placeholder(tf.float32, shape=(2,2))
b = tf.placeholder(tf.float32, shape=(2,3))
mult = tf.matmul(a,b)
init =tf.global_variables_initializer() # para inicializar las variables
sess = tf.Session() # para empezar a correr la grafica computacional
sess.run(init)
print (sess.run(mult,feed_dict={a:[[1,2],[2,2]], b:[[12,21,4],[3,2,4]]}))

[[18. 25. 12.]
 [30. 46. 16.]]


In [55]:
c = tf.placeholder(tf.float32, shape=(3))
d = tf.placeholder(tf.float32, shape=(3))
punto = tf.tensordot(c,d,1) #producto punto entre dos vectores
init = tf.global_variables_initializer() # para inicializar las variables
sess = tf.Session() # para empezar a correr la grafica computacional
sess.run(init)
print (sess.run(punto,feed_dict={c:[1,2,3], d:[3,2,1]}))


10.0
